### ISSUE TITLE
Workflow is not run?

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-cie#1]
For some reason the workflows stopped 28 days ago?

**Comment by andrew2net** [comment]
GitHub disabled it because no updates for 60 days.
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/5623890/131303977-284e8e2b-b7a0-456a-800c-a385c3d183f1.png">

**Comment by andrew2net** [comment]
@ronaldtse I've enabled all the relaton-data-* scheduled workflows but if they won't be updated for 60 days GitHub will block them again. Shouldn't we make a fake file and update it every time?

**Comment by ronaldtse** [comment]
Looks like people do implement a fake commit to prevent this from happening:
e.g. https://github.com/connorads/stackoverflow-fanatic/pull/11
